#-*-makefile-*-

# FIXME : TODO
# export PATH=$PATH:/opt/sparc-elf-3.4.4/bin/

CC = sparc-elf-gcc 
AR = sparc-elf-ar
LD = sparc-elf-ld
STRIP = sparc-elf-strip
OBJCOPY = sparc-elf-objcopy
OBJDUMP	= sparc-elf-objdump
SIMULATION ?=

INCS = -I../include
OPTLVL = -O0 -g
###OPTLVL = -Os -g
# FIXME : DEBUG
#CFLAGS = $(OPTLVL) $(INCS) -Wall -std=gnu99 -nostdlib -nostdinc -msoft-float -mcpu=v8 -DEMBEDDED -Werror
CFLAGS = $(OPTLVL) $(INCS) -Wall -std=gnu99 -nostdlib -nostdinc -msoft-float -mcpu=v8 -DEMBEDDED
ASFLAGS = $(INCS)

DEFINES = $(SIMULATION)

CFLAGS += $(DEFINES)
ASFLAGS += $(DEFINES)

%.o: %.c
	$(CC) -c $(CFLAGS) -o $@ $<

%.o: %.S
	$(CC) -c $(ASFLAGS) -o $@ $<

%.dat: %.exe
	$(OBJDUMP) -s $< > $@

%.srec: %.exe
	$(OBJCOPY) --srec-forceS3 -O srec $< $@
